### ISSUE TITLE
systemd-journal-dev package is obsolete in ubuntu 15.10

### ISSUE THREAD

**Issue by gregl83** [systemd/node-systemd#13]
**NPM module install**

```
Package libsystemd-journal was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsystemd-journal.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsystemd-journal' found
gyp: Call to 'pkg-config --libs-only-l libsystemd-journal' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-22-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure"
gyp ERR! cwd /home/ubuntu/Source/node-systemd
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

npm ERR! Linux 4.2.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! journald@0.0.5 preinstall: `node-gyp clean && node-gyp configure`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the journald@0.0.5 preinstall script 'node-gyp clean && node-gyp configure'.
npm ERR! This is most likely a problem with the journald package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp clean && node-gyp configure
npm ERR! You can get their info via:
npm ERR!     npm owner ls journald
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/Source/node-systemd/npm-debug.log
```

**apt-get install libsystemd-journal-dev**

```
sudo apt-get install libsystemd-journal-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libsystemd-journal-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libsystemd-dev:i386 libsystemd-dev

E: Package 'libsystemd-journal-dev' has no installation candidate
```

**Comment by patrys** [comment]
While this file still exists on Fedora:

```
$ cat /usr/lib64/pkgconfig/libsystemd-journal.pc
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include

Name: systemd
Description: systemd Journal Utility Library - deprecated
URL: http://www.freedesktop.org/wiki/Software/systemd
Version: 222
Requires: libsystemd = 222
Libs: -L${libdir} -lsystemd
Cflags: -I${includedir}
```

Notice it says «deprecated».

**Comment by aptro** [comment]
libsystemd-dev worked for me with ubuntu 16.04LTS

**Comment by gregl83** [comment]
```
user@ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
user@ubuntu:~$ apt-cache search libsystemd
libsystemd-dev - systemd utility library - development files
libsystemd0 - systemd utility library
python3-systemd - Python 3 bindings for systemd
python-systemd - Python 2 bindings for systemd
```

http://packages.ubuntu.com/xenial/libsystemd-journal-dev
