### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by M2Ys4U** [systemd/node-systemd#4]
When trying to install through npm I encounter this error:

```
$ npm install
npm WARN package.json journald@0.0.3 No repository field.

> journald@0.0.3 preinstall /home/m2ys4u/node-systemd
> node-gyp clean && node-gyp configure


> journald@0.0.3 install /home/m2ys4u/node-systemd
> node-gyp build

make: Entering directory '/home/m2ys4u/node-systemd/build'
  CXX(target) Release/obj.target/journald_cpp/src/journald_cpp.o
../src/journald_cpp.cc: In function ‘v8::Handle<v8::Value> SdJournalSend(const v8::Arguments&)’:
../src/journald_cpp.cc:76:89: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
     int status = uv_queue_work(uv_default_loop(), &baton->request, AsyncWork, AsyncAfter);
                                                                                         ^
In file included from /home/m2ys4u/.node-gyp/0.10.26/src/node.h:61:0,
                 from ../src/journald_cpp.cc:11:
/home/m2ys4u/.node-gyp/0.10.26/deps/uv/include/uv.h:1432:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
 UV_EXTERN int uv_queue_work(uv_loop_t* loop, uv_work_t* req,
               ^
journald_cpp.target.mk:82: recipe for target 'Release/obj.target/journald_cpp/src/journald_cpp.o' failed
make: *** [Release/obj.target/journald_cpp/src/journald_cpp.o] Error 1
make: Leaving directory '/home/m2ys4u/node-systemd/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.6-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/m2ys4u/node-systemd
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 

npm ERR! journald@0.0.3 install: `node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the journald@0.0.3 install script.
npm ERR! This is most likely a problem with the journald package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls journald
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.6-1-ARCH
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/m2ys4u/node-systemd
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/m2ys4u/node-systemd/npm-debug.log
npm ERR! not ok code 0
```

**Comment by davidstrauss** [comment]
Yep, there was an API change.

Here's a related issue: https://github.com/joeferner/node-portaudio/issues/4

**Comment by davidstrauss** [comment]
I think pull request #5 will fix this issue, but I need to confirm with the maintainer.

**Comment by marktheunissen** [comment]
Please try the latest master and reopen if it is still an issue.

**Comment by binarybucks** [comment]
It might not be the same issue, but I'm also unable to compile the module 

```
../src/journald_cpp.cc:19:27: error: ‘Arguments’ does not name a type
 Handle<Value> Async(const Arguments& args);
                           ^
../src/journald_cpp.cc:19:38: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 Handle<Value> Async(const Arguments& args);
                                      ^
../src/journald_cpp.cc:20:16: error: variable or field ‘AsyncWork’ declared void
 void AsyncWork(uv_work_t* req);
                ^
../src/journald_cpp.cc:20:16: error: ‘uv_work_t’ was not declared in this scope
../src/journald_cpp.cc:20:27: error: ‘req’ was not declared in this scope
 void AsyncWork(uv_work_t* req);
                           ^
../src/journald_cpp.cc:21:17: error: variable or field ‘AsyncAfter’ declared void
 void AsyncAfter(uv_work_t* req);
                 ^
../src/journald_cpp.cc:21:17: error: ‘uv_work_t’ was not declared in this scope
../src/journald_cpp.cc:21:28: error: ‘req’ was not declared in this scope
 void AsyncAfter(uv_work_t* req);
                            ^
../src/journald_cpp.cc:24:5: error: ‘uv_work_t’ does not name a type
     uv_work_t request;
     ^
../src/journald_cpp.cc:37:35: error: ‘Arguments’ does not name a type
 Handle<Value> SdJournalSend(const Arguments& args) {
                                   ^
../src/journald_cpp.cc:37:46: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 Handle<Value> SdJournalSend(const Arguments& args) {
                                              ^
In file included from /home/alexander/.node-gyp/0.12.2/src/node.h:61:0,
                 from ../src/journald_cpp.cc:11:
/home/alexander/.node-gyp/0.12.2/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> SdJournalSend(const int&)’:
/home/alexander/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/journald_cpp.cc:38:15: error: within this context
   HandleScope scope;
              ^
../src/journald_cpp.cc:39:19: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
   int argc = args.Length();
                   ^
../src/journald_cpp.cc:45:18: error: invalid types ‘const int[int]’ for array subscript
   if (args[argc-1]->IsFunction()) {
                  ^
../src/journald_cpp.cc:55:27: error: ‘New’ is not a member of ‘v8::String’
     return ThrowException(String::New("Out of memory"));
                           ^
../src/journald_cpp.cc:55:55: error: ‘ThrowException’ was not declared in this scope
     return ThrowException(String::New("Out of memory"));
                                                       ^
../src/journald_cpp.cc:58:33: error: invalid types ‘const int[int]’ for array subscript
     Local<String> v8str = args[i]->ToString();
                                 ^
../src/journald_cpp.cc:61:12: error: ‘class v8::String’ has no member named ‘WriteAscii’
     v8str->WriteAscii((char*)iov[i].iov_base, 0, iov[i].iov_len);
            ^
../src/journald_cpp.cc:66:63: error: invalid types ‘const int[int]’ for array subscript
     Local<Function> callback = Local<Function>::Cast(args[argc]);
                                                               ^
../src/journald_cpp.cc:71:12: error: ‘struct Baton’ has no member named ‘request’
     baton->request.data = baton;
            ^
../src/journald_cpp.cc:72:57: error: no matching function for call to ‘v8::Persistent<v8::Function>::New(v8::Local<v8::Function>&)’
     baton->callback = Persistent<Function>::New(callback);
                                                         ^
../src/journald_cpp.cc:72:57: note: candidate is:
In file included from /home/alexander/.node-gyp/0.12.2/src/node.h:61:0,
                 from ../src/journald_cpp.cc:11:
/home/alexander/.node-gyp/0.12.2/deps/v8/include/v8.h:5809:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::Function]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/home/alexander/.node-gyp/0.12.2/deps/v8/include/v8.h:5809:4: note:   candidate expects 2 arguments, 1 provided
../src/journald_cpp.cc:76:48: error: ‘uv_default_loop’ was not declared in this scope
     int status = uv_queue_work(uv_default_loop(), &baton->request, AsyncWork, (uv_after_work_cb) AsyncAfter);
../src/journald_cpp.cc:76:59: error: ‘struct Baton’ has no member named ‘request’
     int status = uv_queue_work(uv_default_loop(), &baton->request, AsyncWork, (uv_after_work_cb) AsyncAfter);
                                                           ^
../src/journald_cpp.cc:76:68: error: ‘AsyncWork’ was not declared in this scope
     int status = uv_queue_work(uv_default_loop(), &baton->request, AsyncWork, (uv_after_work_cb) AsyncAfter);
                                                                    ^
../src/journald_cpp.cc:76:80: error: ‘uv_after_work_cb’ was not declared in this scope
     int status = uv_queue_work(uv_default_loop(), &baton->request, AsyncWork, (uv_after_work_cb) AsyncAfter);
                                                                                ^
../src/journald_cpp.cc:76:108: error: ‘uv_queue_work’ was not declared in this scope
     int status = uv_queue_work(uv_default_loop(), &baton->request, AsyncWork, (uv_after_work_cb) AsyncAfter);
                                                                                                            ^
../src/journald_cpp.cc:87:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(Undefined());
                ^
../src/journald_cpp.cc:87:32: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
   return scope.Close(Undefined());
                                ^
In file included from /home/alexander/.node-gyp/0.12.2/src/node.h:61:0,
                 from ../src/journald_cpp.cc:11:
/home/alexander/.node-gyp/0.12.2/deps/v8/include/v8.h:305:28: note: declared here
   friend Handle<Primitive> Undefined(Isolate* isolate);
                            ^
../src/journald_cpp.cc: At global scope:
../src/journald_cpp.cc:93:16: error: variable or field ‘AsyncWork’ declared void
 void AsyncWork(uv_work_t* req) {
                ^
../src/journald_cpp.cc:93:16: error: ‘uv_work_t’ was not declared in this scope
../src/journald_cpp.cc:93:27: error: ‘req’ was not declared in this scope
 void AsyncWork(uv_work_t* req) {
                           ^
../src/journald_cpp.cc: In function ‘v8::Handle<v8::Value> SdJournalSend(const int&)’:
../src/journald_cpp.cc:88:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/journald_cpp/src/journald_cpp.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.10.0-123.8.1.el7.x86_64
gyp ERR! command "node" "/usr/local/nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /var/www/traction-dev/node_modules/journald
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Linux 3.10.0-123.8.1.el7.x86_64
npm ERR! argv "/usr/local/nvm/versions/node/v0.12.2/bin/node" "/usr/local/nvm/versions/node/v0.12.2/bin/npm" "install" "--save" "journald"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! journald@0.0.5 install: `node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the journald@0.0.5 install script 'node-gyp build'.
npm ERR! This is most likely a problem with the journald package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls journald
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

Used systemd packages are: 

```
$ rpm -qa | grep systemd
systemd-devel-208-20.el7_1.3.x86_64
systemd-libs-208-20.el7_1.3.x86_64
systemd-208-20.el7_1.3.x86_64
systemd-sysv-208-20.el7_1.3.x86_64
```

OS is CentOS 7

```
CentOS Linux release 7.1.1503 (Core)
```

Node version is

```
$ node -v
v0.12.2
```

Any help is greatly appreciated, thanks.
